name=input("What is your name? : ")
print ("Happy Birthday to you")
print ("Happy Birthday to you")
print ("Happy Birthday dear " + name)
print ("Happy Birthday " + name)
print ("")
amber=input ("Do you want to continue? Y/N: ")
if amber=="y" or amber=="Y":
 print ("Happy Birthday to you") 
 print ("Happy Birthday to you")
 print ("Happy Birthday dear " + name)
 print ("Happy Birthday " + name)
 print ("")
else:
  print ("Thank You for listening!! ")
